import { demoAuth } from "./src/mock/auth";

export default {
  appId: "main-b",
  projectType: "PORTAL",
  locale: "zh-CN",
  framework: "react",
  auth: demoAuth,
  dev: { port: 9002 },
  portal: { code: "main-b", menuRootCode: "portal-main-b", permissionPrefix: "portal-main-b" },
  portalSlots: { source: "./src/portal-slots.tsx" },
  layout: {
    preset: "topbar",
    tabs: false,
    breadcrumb: false,
    brandLabel: "Biu",
    brandSubtitle: "Analytics Portal",
    showSearch: true,
    showNotifications: true,
    toolbarIconOnly: true,
    user: { name: "演示用户", role: "Portal User" },
  },
  menu: { fallback: true },
  localMenuTree: [
    {
      code: "system-config",
      type: "DIRECTORY",
      titleKey: "系统配置 System Configuration",
      icon: "settings",
      children: [
        {
          code: "basic-settings",
          type: "DIRECTORY",
          titleKey: "基础设置 Basic Settings",
          children: [
            {
              code: "Overview",
              type: "MENU",
              target: "PORTAL",
              titleKey: "配置概览 Configuration Overview",
              path: "/system-config/basic-settings/Overview",
            },
            {
              code: "PageB",
              type: "MENU",
              target: "APP",
              titleKey: "基础参数维护 Basic Parameters",
              appId: "child-app",
              appPath: "/PageB",
              path: "/system-config/basic-settings/PageB",
            },
            {
              code: "Integration",
              type: "MENU",
              target: "APP",
              titleKey: "外部集成 External Integration",
              appId: "child-app",
              appPath: "/PageB",
              path: "/system-config/basic-settings/Integration",
            },
          ],
        },
        {
          code: "access-control",
          type: "DIRECTORY",
          titleKey: "访问控制 Access Control",
          children: [
            {
              code: "RoleManagement",
              type: "MENU",
              target: "APP",
              titleKey: "角色与权限 Role Management",
              appId: "child-app",
              appPath: "/PageB",
              path: "/system-config/access-control/RoleManagement",
            },
            {
              code: "AccountPolicy",
              type: "MENU",
              target: "APP",
              titleKey: "账户策略 Account Policy",
              appId: "child-app",
              appPath: "/PageB",
              path: "/system-config/access-control/AccountPolicy",
            },
            {
              code: "AuditRules",
              type: "MENU",
              target: "APP",
              titleKey: "审计规则 Audit Rules",
              appId: "child-app",
              appPath: "/PageB",
              path: "/system-config/access-control/AuditRules",
            },
          ],
        },
      ],
    },
    {
      code: "operations-center",
      type: "DIRECTORY",
      titleKey: "运营管理 Operations Center",
      icon: "workspace",
      children: [
        {
          code: "daily-operations",
          type: "DIRECTORY",
          titleKey: "日常运营 Daily Operations",
          children: [
            {
              code: "Dashboard",
              type: "MENU",
              target: "APP",
              titleKey: "运营总览 Operations Dashboard",
              appId: "child-app",
              appPath: "/PageB",
              path: "/operations-center/daily-operations/Dashboard",
            },
            {
              code: "WorkQueue",
              type: "MENU",
              target: "APP",
              titleKey: "工作队列 Work Queue",
              appId: "child-app",
              appPath: "/PageB",
              path: "/operations-center/daily-operations/WorkQueue",
            },
            {
              code: "ServiceCatalog",
              type: "MENU",
              target: "APP",
              titleKey: "服务目录 Service Catalog",
              appId: "child-app",
              appPath: "/PageB",
              path: "/operations-center/daily-operations/ServiceCatalog",
            },
          ],
        },
        {
          code: "report-center",
          type: "DIRECTORY",
          titleKey: "报表中心 Reporting Center",
          children: [
            {
              code: "SummaryReport",
              type: "MENU",
              target: "APP",
              titleKey: "运营汇总 Operations Summary",
              appId: "child-app",
              appPath: "/PageB",
              path: "/operations-center/report-center/SummaryReport",
            },
            {
              code: "TrendAnalysis",
              type: "MENU",
              target: "APP",
              titleKey: "趋势分析 Trend Analysis",
              appId: "child-app",
              appPath: "/PageB",
              path: "/operations-center/report-center/TrendAnalysis",
            },
          ],
        },
      ],
    },
    {
      code: "log-center",
      type: "DIRECTORY",
      titleKey: "日志中心 Log Center",
      icon: "folder",
      children: [
        {
          code: "audit-logs",
          type: "DIRECTORY",
          titleKey: "审计日志 Audit Logs",
          children: [
            {
              code: "LoginHistory",
              type: "MENU",
              target: "APP",
              titleKey: "登录记录 Login History",
              appId: "child-app",
              appPath: "/PageB",
              path: "/log-center/audit-logs/LoginHistory",
            },
            {
              code: "OperationHistory",
              type: "MENU",
              target: "APP",
              titleKey: "操作记录 Operation History",
              appId: "child-app",
              appPath: "/PageB",
              path: "/log-center/audit-logs/OperationHistory",
            },
          ],
        },
        {
          code: "runtime-logs",
          type: "DIRECTORY",
          titleKey: "运行日志 Runtime Logs",
          children: [
            {
              code: "ServiceLogs",
              type: "MENU",
              target: "APP",
              titleKey: "服务日志 Service Logs",
              appId: "child-app",
              appPath: "/PageB",
              path: "/log-center/runtime-logs/ServiceLogs",
            },
            {
              code: "ErrorLogs",
              type: "MENU",
              target: "APP",
              titleKey: "错误日志 Error Logs",
              appId: "child-app",
              appPath: "/PageB",
              path: "/log-center/runtime-logs/ErrorLogs",
            },
          ],
        },
      ],
    },
    {
      code: "security-compliance",
      type: "DIRECTORY",
      titleKey: "安全合规 Security Compliance",
      icon: "folder",
      children: [
        {
          code: "Overview",
          type: "MENU",
          target: "PORTAL",
          titleKey: "合规概览 Compliance Overview",
          path: "/security-compliance/Overview",
        },
        {
          code: "ComplianceReport",
          type: "MENU",
          target: "APP",
          titleKey: "合规报告 Compliance Report",
          appId: "child-app",
          appPath: "/PageB",
          path: "/security-compliance/ComplianceReport",
        },
        {
          code: "PolicyCenter",
          type: "MENU",
          target: "APP",
          titleKey: "制度中心 Policy Center",
          appId: "child-app",
          appPath: "/PageB",
          path: "/security-compliance/PolicyCenter",
        },
      ],
    },
    { code: "Overview", type: "MENU", target: "PORTAL", titleKey: "门户首页 Portal Home", path: "/Overview" },
    {
      code: "PageB",
      type: "MENU",
      target: "APP",
      titleKey: "共享页面 Shared Page",
      appId: "child-app",
      appPath: "/PageB",
      path: "/PageB",
    },
  ],
  routes: { files: ["local-routes/index.ts"] },
};
