export default [
  {
    code: "PageA",
    type: "MENU",
    target: "APP",
    source: "APP",
    titleKey: "PageA",
    appId: "child-app",
    appPath: "/PageA",
  },
  {
    code: "VuePage",
    type: "MENU",
    target: "APP",
    source: "APP",
    titleKey: "Vue 3 子应用",
    appId: "vue-child",
    appPath: "/VuePage",
  },
  {
    code: "Dashboard",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "A 门户概览",
    path: "/Dashboard",
  },
  {
    code: "FoundationShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "基座能力验收 Foundation Showcase",
    path: "/FoundationShowcase",
  },
  {
    code: "PlatformCapabilities",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "基座能力展示",
    path: "/PlatformCapabilities",
  },
  {
    code: "RuntimeCapabilities",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "Runtime 能力展示",
    path: "/RuntimeCapabilities",
  },
  {
    code: "RouterMenuShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "路由与菜单展示",
    path: "/RouterMenuShowcase",
  },
  {
    code: "OverlayShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "Drawer / Dialog 展示",
    path: "/OverlayShowcase",
  },
  {
    code: "TooltipEllipsisShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "Tooltip / Ellipsis 展示",
    path: "/TooltipEllipsisShowcase",
  },
  {
    code: "ComponentUIShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "组件能力展示",
    path: "/ComponentUIShowcase",
  },
  {
    code: "IconsSearch",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "Icons 快速查询",
    path: "/IconsSearch",
  },
  {
    code: "FormShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "Form 能力展示",
    path: "/FormShowcase",
  },
  {
    code: "TableShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "Table 能力展示",
    path: "/TableShowcase",
  },
  {
    code: "HttpShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "HTTP 能力展示",
    path: "/HttpShowcase",
  },
  {
    code: "I18nShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "i18n 能力展示",
    path: "/I18nShowcase",
  },
  {
    code: "TanstackQueryShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "TanStack Query 能力展示",
    path: "/TanstackQueryShowcase",
  },
  {
    code: "StoreShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "Store 能力展示",
    path: "/StoreShowcase",
  },
  {
    code: "RenderCodeShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "Render Code 能力展示",
    path: "/RenderCodeShowcase",
  },
  {
    code: "WatermarkShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "Watermark 能力展示",
    path: "/WatermarkShowcase",
  },
  {
    code: "LoggerShowcase",
    type: "MENU",
    target: "PORTAL",
    source: "PORTAL",
    titleKey: "Logger 能力展示",
    path: "/LoggerShowcase",
  },
];
