import * as React from "react";
import { ArrowDown, ArrowUp, GripVertical, Trash2 } from "@biugle/icons";
import { Button, Tooltip } from "@biugle/react-components";
import { CircleHelp } from "@biugle/icons";
import { useBiuFormLocale } from "./context.js";
import type { BiuFormLocale, BiuFormLocaleTextOverrides } from "../locale/index.js";
import {
  useFieldArray,
  useFormContext,
  type Control,
  type FieldArray,
  type FieldArrayPath,
  type FieldValues,
  type UseFieldArrayProps,
} from "react-hook-form";

export interface FormListField {
  /** Stable React key generated by react-hook-form. */
  key: string;
  /** Current array index used to build nested Form.Item names. */
  name: number;
  index: number;
}

export interface FormListOperations<TItem = unknown> {
  add: (value?: TItem, index?: number) => void;
  remove: (index: number | number[]) => void;
  move: (from: number, to: number) => void;
  replace: (values: TItem[]) => void;
}

export interface FormListMeta {
  errors?: unknown;
  canAdd: boolean;
  canRemove: boolean;
  minRows: number;
  maxRows: number;
}

export interface FormListColumnRenderContext<TItem = unknown> {
  /** Current item index in the field array. */
  index: number;
  /** Stable field identity and index metadata. */
  field: FormListField;
  /** The complete array field path, for example `contacts.0.name`. */
  fieldName: string;
  /** Current field value exposed for read-only or derived rendering. */
  value: TItem;
  /** The same add/remove/move/replace operations exposed to children. */
  operations: FormListOperations<TItem>;
}

export interface FormListColumn<TItem = unknown> {
  key: string;
  label?: React.ReactNode;
  tooltip?: React.ReactNode;
  name: string;
  width?: number | string;
  render: (context: FormListColumnRenderContext<TItem>) => React.ReactNode;
}

export interface FormListClassNames {
  root?: string;
  field?: string;
  header?: string;
  row?: string;
  column?: string;
  actions?: string;
  remove?: string;
  sort?: string;
  sortHandle?: string;
  sortIndex?: string;
  operation?: string;
  move?: string;
}

export interface FormListProps<
  TFieldValues extends FieldValues = FieldValues,
  TFieldArrayName extends FieldArrayPath<TFieldValues> = FieldArrayPath<TFieldValues>,
> {
  name: TFieldArrayName;
  control?: Control<TFieldValues>;
  rules?: UseFieldArrayProps<TFieldValues, TFieldArrayName>["rules"];
  initialValue?: Array<FieldArray<TFieldValues, TFieldArrayName>>;
  /** Value used by the generated add button in columns mode. */
  addValue?: FieldArray<TFieldValues, TFieldArrayName>;
  children?: (
    fields: FormListField[],
    operations: FormListOperations<FieldArray<TFieldValues, TFieldArrayName>>,
    meta: FormListMeta,
  ) => React.ReactNode;
  /** Optional table-like field definitions for one-row/multi-control lists. */
  columns?: Array<FormListColumn<FieldArray<TFieldValues, TFieldArrayName>>>;
  addText?: React.ReactNode;
  removeText?: React.ReactNode;
  showAdd?: boolean;
  showRemove?: boolean;
  /** Minimum number of rows. Values are clamped to 0..99999. */
  minRows?: number;
  /** Maximum number of rows. Values are clamped to 0..99999. */
  maxRows?: number;
  /** Allow native drag sorting in columns mode. Defaults to true. */
  sortable?: boolean;
  /** Show the optional first sorting column with drag/up/down controls. */
  showSort?: boolean;
  /** Show the one-based row number inside the sorting column. */
  showSortIndex?: boolean;
  sortLabel?: React.ReactNode;
  operationLabel?: React.ReactNode;
  locale?: BiuFormLocale;
  localeText?: BiuFormLocaleTextOverrides;
  onSortChange?: (from: number, to: number) => void;
  className?: string;
  classNames?: FormListClassNames;
}

/**
 * Dynamic field-array support compatible with the Form.List pattern used by
 * IMD/design-imile. Field values remain owned by react-hook-form; this
 * component only exposes stable indexes and array operations to the page.
 */
export function List<TFieldValues extends FieldValues, TFieldArrayName extends FieldArrayPath<TFieldValues>>({
  name,
  control,
  rules,
  initialValue,
  addValue,
  children,
  columns,
  addText,
  removeText,
  showAdd = true,
  showRemove = true,
  minRows = 0,
  maxRows = 99999,
  sortable = true,
  showSort = false,
  showSortIndex = false,
  sortLabel,
  operationLabel,
  locale,
  localeText,
  onSortChange,
  className,
  classNames,
}: FormListProps<TFieldValues, TFieldArrayName>) {
  const text = useBiuFormLocale(locale, localeText);
  const resolvedAddText = addText ?? text["新增"];
  const resolvedRemoveText = removeText ?? text["删除"];
  const resolvedSortLabel = sortLabel ?? text["排序"];
  const resolvedOperationLabel = operationLabel ?? text["操作"];
  const form = useFormContext<TFieldValues>();
  const fieldArray = useFieldArray<TFieldValues, TFieldArrayName>({
    control: control ?? form.control,
    name,
    rules,
  });
  const normalizedMinRows = Math.max(0, Math.min(99999, Math.floor(Number(minRows) || 0)));
  const normalizedMaxRows = Math.max(normalizedMinRows, Math.min(99999, Math.floor(Number(maxRows) || 0)));
  const initialized = React.useRef(false);
  const [draggingIndex, setDraggingIndex] = React.useState<number | null>(null);
  const [dropIndex, setDropIndex] = React.useState<number | null>(null);

  React.useEffect(() => {
    if (!initialized.current && initialValue?.length && fieldArray.fields.length === 0) {
      fieldArray.replace(initialValue);
    }
    initialized.current = true;
  }, [fieldArray, initialValue]);

  const fields = fieldArray.fields.map((field, index) => ({
    key: String(field.id),
    name: index,
    index,
  }));
  const operations: FormListOperations<FieldArray<TFieldValues, TFieldArrayName>> = {
    add: (value, index) => {
      if (fieldArray.fields.length >= normalizedMaxRows) return;
      const nextValue = value ?? ({} as FieldArray<TFieldValues, TFieldArrayName>);
      if (index === undefined) fieldArray.append(nextValue);
      else fieldArray.insert(index, nextValue);
    },
    remove: (index) => {
      if (fieldArray.fields.length <= normalizedMinRows) return;
      fieldArray.remove(index);
    },
    move: (from, to) => {
      if (from === to || from < 0 || to < 0 || from >= fieldArray.fields.length || to >= fieldArray.fields.length)
        return;
      fieldArray.move(from, to);
      onSortChange?.(from, to);
    },
    replace: (values) => fieldArray.replace(values as Array<FieldArray<TFieldValues, TFieldArrayName>>),
  };
  const errors = (form.formState.errors as Record<string, unknown>)[String(name)];
  const canAdd = fields.length < normalizedMaxRows;
  const canRemove = fields.length > normalizedMinRows;
  const handleDragStart = (event: React.DragEvent<HTMLDivElement>, index: number) => {
    if (!sortable) {
      event.preventDefault();
      return;
    }
    setDraggingIndex(index);
    event.dataTransfer.effectAllowed = "move";
    event.dataTransfer.setData("text/plain", String(index));
  };
  const handleDragOver = (event: React.DragEvent<HTMLDivElement>, index: number) => {
    if (!sortable || draggingIndex === null || draggingIndex === index) return;
    event.preventDefault();
    event.dataTransfer.dropEffect = "move";
    setDropIndex(index);
  };
  const handleDrop = (event: React.DragEvent<HTMLDivElement>, index: number) => {
    event.preventDefault();
    const source = draggingIndex ?? Number(event.dataTransfer.getData("text/plain"));
    if (sortable && Number.isInteger(source) && source >= 0 && source !== index) operations.move(source, index);
    setDraggingIndex(null);
    setDropIndex(null);
  };
  const clearDrag = () => {
    setDraggingIndex(null);
    setDropIndex(null);
  };
  const renderColumns = () => {
    if (!columns?.length) return null;
    const columnTrack = (width?: number | string) =>
      width === undefined ? "minmax(0, 1fr)" : typeof width === "number" ? `${width}px` : width;
    const gridTemplateColumns = [
      showSort ? "92px" : null,
      ...columns.map((column) => columnTrack(column.width)),
      showRemove ? "40px" : null,
    ]
      .filter(Boolean)
      .join(" ");
    const listGridStyle = { gridTemplateColumns } satisfies React.CSSProperties;
    return (
      <div className={classNames?.field} data-biu-slot="form-list-fields">
        <div className={["biu-form-list__header", classNames?.header].filter(Boolean).join(" ")} style={listGridStyle}>
          {showSort ? (
            <span className={["biu-form-list__sort", classNames?.sort].filter(Boolean).join(" ")}>
              {resolvedSortLabel}
            </span>
          ) : null}
          {columns.map((column) => (
            <span key={column.key} className="biu-form-list__header-label">
              {column.label}
              {column.tooltip ? (
                <Tooltip content={column.tooltip} onlyOverflow={false}>
                  <button
                    type="button"
                    className="biu-form-list__header-tooltip"
                    aria-label={typeof column.tooltip === "string" ? column.tooltip : undefined}
                  >
                    <CircleHelp size={13} aria-hidden="true" />
                  </button>
                </Tooltip>
              ) : null}
            </span>
          ))}
          {showRemove ? <span className="biu-form-list__operation">{resolvedOperationLabel}</span> : null}
        </div>
        {fields.map((field) => (
          <div
            key={field.key}
            className={["biu-form-list__row", classNames?.row].filter(Boolean).join(" ")}
            data-field-index={field.index}
            data-biu-sortable={sortable ? "true" : "false"}
            data-drop-target={dropIndex === field.index ? "true" : undefined}
            draggable={sortable}
            onDragStart={(event) => handleDragStart(event, field.index)}
            onDragOver={(event) => handleDragOver(event, field.index)}
            onDrop={(event) => handleDrop(event, field.index)}
            onDragEnd={clearDrag}
            style={listGridStyle}
          >
            {showSort ? (
              <div className={["biu-form-list__sort", classNames?.sort].filter(Boolean).join(" ")}>
                {showSortIndex ? (
                  <span className={["biu-form-list__sort-index", classNames?.sortIndex].filter(Boolean).join(" ")}>
                    {field.index + 1}
                  </span>
                ) : null}
                <span
                  className={["biu-form-list__sort-handle", classNames?.sortHandle].filter(Boolean).join(" ")}
                  title={text["拖动排序"]}
                  aria-hidden="true"
                >
                  <GripVertical size={15} />
                </span>
                <button
                  type="button"
                  className={["biu-form-list__move", classNames?.move].filter(Boolean).join(" ")}
                  disabled={field.index === 0}
                  aria-label={text["上移"]}
                  title={text["上移"]}
                  onClick={() => operations.move(field.index, field.index - 1)}
                >
                  <ArrowUp size={13} aria-hidden="true" />
                </button>
                <button
                  type="button"
                  className={["biu-form-list__move", classNames?.move].filter(Boolean).join(" ")}
                  disabled={field.index === fields.length - 1}
                  aria-label={text["下移"]}
                  title={text["下移"]}
                  onClick={() => operations.move(field.index, field.index + 1)}
                >
                  <ArrowDown size={13} aria-hidden="true" />
                </button>
              </div>
            ) : null}
            {columns.map((column) => {
              const fieldName = `${String(name)}.${field.index}.${column.name}`;
              return (
                <div
                  key={column.key}
                  className={["biu-form-list__column", classNames?.column].filter(Boolean).join(" ")}
                >
                  {column.render({
                    index: field.index,
                    field,
                    fieldName,
                    value: (fieldArray.fields[field.index] ?? {}) as FieldArray<TFieldValues, TFieldArrayName>,
                    operations: operations as FormListOperations<FieldArray<TFieldValues, TFieldArrayName>>,
                  })}
                </div>
              );
            })}
            {showRemove ? (
              <Button
                type="secondary"
                variant="contained"
                size="small"
                onlyIcon
                icon={<Trash2 size={15} aria-hidden="true" />}
                tooltip={resolvedRemoveText}
                aria-label={typeof resolvedRemoveText === "string" ? resolvedRemoveText : text["删除"]}
                className={["biu-form-list__remove", classNames?.remove].filter(Boolean).join(" ")}
                disabled={!canRemove}
                onClick={() => operations.remove(field.index)}
              />
            ) : null}
          </div>
        ))}
        {showAdd ? (
          <div className={["biu-form-list__actions", classNames?.actions].filter(Boolean).join(" ")}>
            <button type="button" disabled={!canAdd} onClick={() => operations.add(addValue)}>
              {resolvedAddText}
            </button>
          </div>
        ) : null}
      </div>
    );
  };

  return (
    <div
      className={["biu-form-list", className, classNames?.root].filter(Boolean).join(" ")}
      data-field-array-name={String(name)}
    >
      {children
        ? children(fields, operations, {
            errors,
            canAdd,
            canRemove,
            minRows: normalizedMinRows,
            maxRows: normalizedMaxRows,
          })
        : renderColumns()}
    </div>
  );
}
